apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: easy-host
  description: Documentation for easy-host
  annotations:
    github.com/project-slug: frbarbre/easy-host
    backstage.io/techdocs-ref: url:https://mytechdocsstorage.blob.core.windows.net/techdocs/frbarbre/easy-host/
spec:
  type: website
  lifecycle: production
  owner: frbarbre
